imports:
    - 'vendor/opine/framework/config/container.yml'

services:
    controller:
        class:     'Controller'
        arguments: ['@model', '@view']
    model:
        class:     'Model'
        arguments: ['@db']
    view:
        class:     'View'
        arguments: ['@layout']
    helperHeader:
        class:     'Helper\Header'
        arguments: ['@layout']